export const STORAGE_CHANNELS = Object.freeze({
  listWallets: 'storage:wallets:list',
  saveWallet: 'storage:wallets:save',
  removeWallet: 'storage:wallets:remove',
  appendReward: 'storage:rewards:append',
  rewardsForWallet: 'storage:rewards:wallet',
  appendWalletBalanceSnapshot: 'storage:analytics:balance:append',
  walletBalanceSnapshots: 'storage:analytics:balance:wallet',
  saveWalletSessionResult: 'storage:analytics:session:save',
  walletSessionResults: 'storage:analytics:session:wallet',
  appendDiagnostic: 'storage:diagnostics:append',
  recentDiagnostics: 'storage:diagnostics:recent',
  saveSecureValue: 'storage:secure:save',
  hasSecureValue: 'storage:secure:has',
  loadSecureValue: 'storage:secure:load',
  removeSecureValue: 'storage:secure:remove',
  globalMiningUptimeSnapshot: 'storage:uptime:snapshot',
  startGlobalMiningUptime: 'storage:uptime:start',
  heartbeatGlobalMiningUptime: 'storage:uptime:heartbeat',
  stopGlobalMiningUptime: 'storage:uptime:stop',
  loadMainEpochStartSchedule: 'storage:automation:main-epoch-start:load',
  saveMainEpochStartSchedule: 'storage:automation:main-epoch-start:save',
});
